compressionLevel: mixed

enableGlobalCache: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"
  - checksum: b1c1ddcd967b168da2e329ce1fe95ede85b1327032e5fa8725516df4e72a1cddb6c608925def5f1fc7dd64742d1c64cf125bc10753e4f8956872128a4a2d750a
    path: .yarn/plugins/@yarnpkg/plugin-workspace-since.cjs
    spec: "https://raw.githubusercontent.com/toss/yarn-plugin-workspace-since/main/bundles/%40yarnpkg/plugin-workspace-since.js"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.0.2.cjs
