import { Inter } from 'next/font/google';
import StyledComponentsRegistry from '@/lib/registry';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <head>
        <title>당신만을 위한 초대장 💌</title>
        <link
          rel="stylesheet"
          as="style"
          crossOrigin="anonymous"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.7/dist/web/variable/pretendardvariable-dynamic-subset.css"
        />
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0" />
        <meta property="og:url" content="https://omizha.studio/" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="당신만을 위한 초대장 💌" />
        <meta
          property="og:description"
          content="정훈이가 오직 당신만을 위한 초대장을 준비했어요. 한 번 확인해볼까요? ✨"
        />
        <meta property="og:image" content="/thumbnail.png" />
        <link href="/bg.mp4" rel="preload" as="video" type="video/mp4" />
      </head>
      <body
        className={inter.className}
        style={{
          height: '100vh',
          margin: 0,
          overflow: 'hidden',
          width: '100vw',
        }}
      >
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
